books/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('add/', add_books, name='add_new_books'),
    path('download/', download_page, name='download_page'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import home_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('', home_page, name='home'),
]

books/models.py
from django.db import models


# Create your models here.
class Books(models.Model):
    Name = models.CharField(max_length=255)
    Title = models.CharField(max_length=255)
    Author = models.CharField(max_length=100)
    No_of_Copies = models.PositiveIntegerField(default=0)
    Publisher_Name = models.CharField(max_length=255, null=True, blank=True)
    Publish_Date = models.DateField(null=True, blank=True)
    Create_On = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.Name

books/forms.py
from django import forms
from .models import *


class BooksForm(forms.ModelForm):

    class Meta:
        model = Books
        fields = '__all__'

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
import csv
from django.db.models import Q
from datetime import datetime


# Create your views here.
def home_page(request):
    return render(request, 'books/index.html', {})


def add_books(request):
    form = BooksForm()
    if request.method == 'POST':
        form = BooksForm(request.POST)
        if form.is_valid():
            form.save()
            message = "Books has been added !!!"
            return render(request, 'books/add_books.html', {'form': form, 'message': message})
    return render(request, 'books/add_books.html', {'form': form})


def download_page(request):
    if request.method == 'POST':
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        obj_books = Books.objects.filter(Q(Publish_Date__gte=start_date) & Q(Publish_Date__lte=end_date))
        meta = Books._meta
        field_name = [field.name for field in meta.fields]
        filename = "BooksData_" + str(datetime.now().strftime("%d%m%Y%H%M%S")) + ".csv"
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
        writer = csv.writer(response)
        writer.writerow(field_name)
        for obj in obj_books:
            row = writer.writerow([getattr(obj, field) for field in field_name])
        return response
    return render(request, 'books/download_page.html', {})

books/templates/books/add_books.html
{% extends 'books/index.html' %}

{% block content %}


{% if message %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
 <center><strong>{{message}}</strong></center>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<div class="card">
  <div class="card-header">
    Add New Books
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <div class="card-text">
        <form method="post" autocomplete="off">
        {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                    <div class="form-group col-md-3">
                        <label for="start">{{field.label}}</label>
                        {{field}}
                    </div>
                    {% endfor %}
                </div>

        <button class="btn btn-primary" id="btn_submit" type="submit">Save</button>
        </form>
  </div>
  </div>
</div>


<script>
$('form').find(':input,:radio,:checkbox').addClass('form-control');
$('#btn_submit').removeClass('form-control');

$('#id_Publish_Date').addClass('datepicker');
$('#id_Create_On').addClass('datepicker');


// datepicker
$(function () {
$(".datepicker").datepicker({"dateFormat": "yy-mm-dd",
    autoclose: true,
    todayHighlight: true
}).datepicker('update', new Date());
});
</script>

{% endblock %}

books/templates/books/download_page.html
{% extends 'books/index.html' %}

{% block content %}

<div class="card">
    <div class="card-header">
        Download Data
    </div>
    <div class="card-body">
        <div class="card-text">
            <form method="post" autocomplete="off">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="start">Start Date</label>
                        <input type="text" data-date-format="yyyy-mm-dd" class="form-control datepicker" name="start_date" id="start_date" placeholder="YYYY-MM-DD">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="end">End Date</label>
                        <input type="text" data-date-format="yyyy-mm-dd" class="form-control datepicker" name="end_date" id="end_date" placeholder="YYYY-MM-DD">
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Download</button>
            </form>
        </div>
    </div>
</div>

<script>

$(function () {
$(".datepicker").datepicker({"dateFormat": "yy-mm-dd",
    autoclose: true,
    todayHighlight: true
}).datepicker('update', new Date());
});
</script>

{% endblock %}

books/templates/books/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">

    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

    <title>LMS</title>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'add_new_books' %}">Add Books <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'download_page' %}">Download</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  {% block content %}
  {% endblock %}
</div>
    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  </body>
</html>